--- #YAML:1.0
name:               Ogre
version:            0.50
abstract:           Perl binding for the OGRE C++ graphics library
author:
    - Scott Lanning <slanning@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
        - t
        - examples
        - genscripts
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
